# Generated by Django 3.1.7 on 2021-06-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=200, null=True)),
                ('model', models.CharField(max_length=200, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('price_cents', models.IntegerField(null=True)),
                ('rating', models.FloatField(null=True)),
                ('volume_discount_percent', models.IntegerField(null=True)),
                ('volume_discount_threshold', models.IntegerField(null=True)),
                ('color', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
